#!/bin/python3

import sys
import parser
import codegen

src = '''

a = 200 + 2 + 3 + 4 + 4 + 123456789

'''

import pdb; pdb.set_trace()

err, program = parser.parse(src)

if err:
    print(', '.join(err), file=sys.stderr)
    sys.exit(1)

for s in program:
    print(s)

print(codegen.gen(program))